# Generated by Django 4.1.3 on 2022-11-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0002_screen_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='status',
        ),
    ]
